name: Pipeline EPIS Medusa

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Tarea #1: Flujo de Integración Continua (CI)
  Calidad-y-Compilacion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Instalacion de dependencias
        run: pnpm install --frozen-lockfile

      - name: Compilacion del Backend
        run: cd apps/backend && pnpm build
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/medusa"

      - name: Compilacion del Storefront
        run: cd apps/storefront && pnpm build

  # Tarea #10: Dockerizacion y Localizacion
  Verificacion-Docker:
    needs: Calidad-y-Compilacion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image (Prueba de infraestructura)
        run: docker build -t medusa-epis-test .